---
repository:
  description: Template for Symfony project
  homepage: https://github.com/hspaans/symfony-template
  topics: php, symfony, template, project, application
  delete_branch_on_merge: true
  has_wiki: false
